### PR TITLE
added LICENSE and updated README.md

### PR DESCRIPTION
**Pull request by negativenagesh**
@dormeneur 

I have added License which may not require any changes, and regarding README.md if any changes / suggestions required please reply to this freely..

### CODE REVIEW

**Comment by negativenagesh** [comment]
@dormeneur 

Final one looks Very good.. if not give suggestions

**Review by dormeneur — APPROVED** [review]

**Comment by negativenagesh** [comment]
@dormeneur please add hacktoberfest-accepted tag

**Comment by dormeneur** [comment]
Good work here! @negativenagesh 
I will now add the label hacktoberfest-accepted

**Comment by dormeneur** [comment]
real creativity with the GIFs there

**Pull request merged**
